import{a as f,S as y,i as l}from"./assets/vendor-73qhTu8_.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m="55695141-df1ad6569c10fb966400a1286",d="https://pixabay.com/api/";async function g(o){const r={key:m,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await f.get(d,{params:r})).data}const i=document.querySelector(".gallery"),p=document.querySelector(".loader-container");let h=new y(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){return o.map(({webformatURL:r,largeImageURL:s,tags:a,likes:e,views:t,comments:n,downloads:u})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${r}" alt="${a}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes</b><span>${e}</span></p>
            <p class="info-item"><b>Views</b><span>${t}</span></p>
            <p class="info-item"><b>Comments</b><span>${n}</span></p>
            <p class="info-item"><b>Downloads</b><span>${u}</span></p>
          </div>
        </a>
      </li>`).join("")}function L(o){i.style.display="flex";const r=b(o);i.innerHTML=r,h.refresh()}function w(){i.innerHTML="",i.style.display="none"}function P(){p.style.display="flex"}function S(){p.style.display="none"}const c=document.querySelector(".form");c.addEventListener("submit",o=>{o.preventDefault();const r=o.currentTarget.elements.searchQuery.value.trim();if(r===""){l.error({title:"Error",message:"The search field cannot be empty! Please enter a query.",position:"topRight"});return}w(),P(),g(r).then(s=>{if(s.hits.length===0){l.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(s.hits)}).catch(s=>{l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("API Error:",s)}).finally(()=>{S(),c.reset()})});
//# sourceMappingURL=index.js.map
